dubbo:
 application:
  name: shop_service
 registry:
  address: zookeeper://10.20.152.87:2181
spring:
 datasource:
  username: root
  password: root
  url: jdbc:mysql:///shop
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
 type-aliases-package: com.lxh.entity
 mapper-locations: classpath*:com/lxh/shop/dao/mapper/*.xml
server:
  port: 8088